// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.postgres.prisma",
  migrations: {
    path: "prisma/migrations_pg",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Use DATABASE_URL for migrations. If hanging, try:
    // 1. Use Supabase direct connection (db.<project_ref>.supabase.co:5432) in DIRECT_URL
    // 2. Or add ?statement_timeout=30000 to DATABASE_URL
    url: process.env["DATABASE_URL"],
  },
});
